"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertOneCommentArgs = exports.UpdateOneCommentArgs = exports.UpdateManyCommentArgs = exports.GroupByCommentArgs = exports.FindUniqueCommentOrThrowArgs = exports.FindUniqueCommentArgs = exports.FindManyCommentArgs = exports.FindFirstCommentOrThrowArgs = exports.FindFirstCommentArgs = exports.DeleteOneCommentArgs = exports.DeleteManyCommentArgs = exports.CreateOneCommentArgs = exports.AggregateCommentArgs = void 0;
var AggregateCommentArgs_1 = require("./AggregateCommentArgs");
Object.defineProperty(exports, "AggregateCommentArgs", { enumerable: true, get: function () { return AggregateCommentArgs_1.AggregateCommentArgs; } });
var CreateOneCommentArgs_1 = require("./CreateOneCommentArgs");
Object.defineProperty(exports, "CreateOneCommentArgs", { enumerable: true, get: function () { return CreateOneCommentArgs_1.CreateOneCommentArgs; } });
var DeleteManyCommentArgs_1 = require("./DeleteManyCommentArgs");
Object.defineProperty(exports, "DeleteManyCommentArgs", { enumerable: true, get: function () { return DeleteManyCommentArgs_1.DeleteManyCommentArgs; } });
var DeleteOneCommentArgs_1 = require("./DeleteOneCommentArgs");
Object.defineProperty(exports, "DeleteOneCommentArgs", { enumerable: true, get: function () { return DeleteOneCommentArgs_1.DeleteOneCommentArgs; } });
var FindFirstCommentArgs_1 = require("./FindFirstCommentArgs");
Object.defineProperty(exports, "FindFirstCommentArgs", { enumerable: true, get: function () { return FindFirstCommentArgs_1.FindFirstCommentArgs; } });
var FindFirstCommentOrThrowArgs_1 = require("./FindFirstCommentOrThrowArgs");
Object.defineProperty(exports, "FindFirstCommentOrThrowArgs", { enumerable: true, get: function () { return FindFirstCommentOrThrowArgs_1.FindFirstCommentOrThrowArgs; } });
var FindManyCommentArgs_1 = require("./FindManyCommentArgs");
Object.defineProperty(exports, "FindManyCommentArgs", { enumerable: true, get: function () { return FindManyCommentArgs_1.FindManyCommentArgs; } });
var FindUniqueCommentArgs_1 = require("./FindUniqueCommentArgs");
Object.defineProperty(exports, "FindUniqueCommentArgs", { enumerable: true, get: function () { return FindUniqueCommentArgs_1.FindUniqueCommentArgs; } });
var FindUniqueCommentOrThrowArgs_1 = require("./FindUniqueCommentOrThrowArgs");
Object.defineProperty(exports, "FindUniqueCommentOrThrowArgs", { enumerable: true, get: function () { return FindUniqueCommentOrThrowArgs_1.FindUniqueCommentOrThrowArgs; } });
var GroupByCommentArgs_1 = require("./GroupByCommentArgs");
Object.defineProperty(exports, "GroupByCommentArgs", { enumerable: true, get: function () { return GroupByCommentArgs_1.GroupByCommentArgs; } });
var UpdateManyCommentArgs_1 = require("./UpdateManyCommentArgs");
Object.defineProperty(exports, "UpdateManyCommentArgs", { enumerable: true, get: function () { return UpdateManyCommentArgs_1.UpdateManyCommentArgs; } });
var UpdateOneCommentArgs_1 = require("./UpdateOneCommentArgs");
Object.defineProperty(exports, "UpdateOneCommentArgs", { enumerable: true, get: function () { return UpdateOneCommentArgs_1.UpdateOneCommentArgs; } });
var UpsertOneCommentArgs_1 = require("./UpsertOneCommentArgs");
Object.defineProperty(exports, "UpsertOneCommentArgs", { enumerable: true, get: function () { return UpsertOneCommentArgs_1.UpsertOneCommentArgs; } });
