services:

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
      - dist:/usr/share/nginx/html/assets/js
    depends_on:
      - graphql-server

  graphql-server:
    image: node:18-alpine
    command: sh -c "npm install && npm run graphql-server-dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - dist:/app/dist
      - node_modules:/app/node_modules
    depends_on:
      - webpack
      - db

  webpack:
    image: node:18-alpine
    command: sh -c "npm install && npm run watch"
    working_dir: /app
    volumes:
      - ./:/app
      - dist:/app/dist
      - node_modules:/app/node_modules

volumes:
  dist:
  node_modules:
  db:
