"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertOnePostHistoryArgs = exports.UpdateOnePostHistoryArgs = exports.UpdateManyPostHistoryArgs = exports.GroupByPostHistoryArgs = exports.FindUniquePostHistoryOrThrowArgs = exports.FindUniquePostHistoryArgs = exports.FindManyPostHistoryArgs = exports.FindFirstPostHistoryOrThrowArgs = exports.FindFirstPostHistoryArgs = exports.DeleteOnePostHistoryArgs = exports.DeleteManyPostHistoryArgs = exports.CreateOnePostHistoryArgs = exports.AggregatePostHistoryArgs = void 0;
var AggregatePostHistoryArgs_1 = require("./AggregatePostHistoryArgs");
Object.defineProperty(exports, "AggregatePostHistoryArgs", { enumerable: true, get: function () { return AggregatePostHistoryArgs_1.AggregatePostHistoryArgs; } });
var CreateOnePostHistoryArgs_1 = require("./CreateOnePostHistoryArgs");
Object.defineProperty(exports, "CreateOnePostHistoryArgs", { enumerable: true, get: function () { return CreateOnePostHistoryArgs_1.CreateOnePostHistoryArgs; } });
var DeleteManyPostHistoryArgs_1 = require("./DeleteManyPostHistoryArgs");
Object.defineProperty(exports, "DeleteManyPostHistoryArgs", { enumerable: true, get: function () { return DeleteManyPostHistoryArgs_1.DeleteManyPostHistoryArgs; } });
var DeleteOnePostHistoryArgs_1 = require("./DeleteOnePostHistoryArgs");
Object.defineProperty(exports, "DeleteOnePostHistoryArgs", { enumerable: true, get: function () { return DeleteOnePostHistoryArgs_1.DeleteOnePostHistoryArgs; } });
var FindFirstPostHistoryArgs_1 = require("./FindFirstPostHistoryArgs");
Object.defineProperty(exports, "FindFirstPostHistoryArgs", { enumerable: true, get: function () { return FindFirstPostHistoryArgs_1.FindFirstPostHistoryArgs; } });
var FindFirstPostHistoryOrThrowArgs_1 = require("./FindFirstPostHistoryOrThrowArgs");
Object.defineProperty(exports, "FindFirstPostHistoryOrThrowArgs", { enumerable: true, get: function () { return FindFirstPostHistoryOrThrowArgs_1.FindFirstPostHistoryOrThrowArgs; } });
var FindManyPostHistoryArgs_1 = require("./FindManyPostHistoryArgs");
Object.defineProperty(exports, "FindManyPostHistoryArgs", { enumerable: true, get: function () { return FindManyPostHistoryArgs_1.FindManyPostHistoryArgs; } });
var FindUniquePostHistoryArgs_1 = require("./FindUniquePostHistoryArgs");
Object.defineProperty(exports, "FindUniquePostHistoryArgs", { enumerable: true, get: function () { return FindUniquePostHistoryArgs_1.FindUniquePostHistoryArgs; } });
var FindUniquePostHistoryOrThrowArgs_1 = require("./FindUniquePostHistoryOrThrowArgs");
Object.defineProperty(exports, "FindUniquePostHistoryOrThrowArgs", { enumerable: true, get: function () { return FindUniquePostHistoryOrThrowArgs_1.FindUniquePostHistoryOrThrowArgs; } });
var GroupByPostHistoryArgs_1 = require("./GroupByPostHistoryArgs");
Object.defineProperty(exports, "GroupByPostHistoryArgs", { enumerable: true, get: function () { return GroupByPostHistoryArgs_1.GroupByPostHistoryArgs; } });
var UpdateManyPostHistoryArgs_1 = require("./UpdateManyPostHistoryArgs");
Object.defineProperty(exports, "UpdateManyPostHistoryArgs", { enumerable: true, get: function () { return UpdateManyPostHistoryArgs_1.UpdateManyPostHistoryArgs; } });
var UpdateOnePostHistoryArgs_1 = require("./UpdateOnePostHistoryArgs");
Object.defineProperty(exports, "UpdateOnePostHistoryArgs", { enumerable: true, get: function () { return UpdateOnePostHistoryArgs_1.UpdateOnePostHistoryArgs; } });
var UpsertOnePostHistoryArgs_1 = require("./UpsertOnePostHistoryArgs");
Object.defineProperty(exports, "UpsertOnePostHistoryArgs", { enumerable: true, get: function () { return UpsertOnePostHistoryArgs_1.UpsertOnePostHistoryArgs; } });
