"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = exports.PostHistory = exports.Post = exports.Comment = void 0;
var Comment_1 = require("./Comment");
Object.defineProperty(exports, "Comment", { enumerable: true, get: function () { return Comment_1.Comment; } });
var Post_1 = require("./Post");
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return Post_1.Post; } });
var PostHistory_1 = require("./PostHistory");
Object.defineProperty(exports, "PostHistory", { enumerable: true, get: function () { return PostHistory_1.PostHistory; } });
var User_1 = require("./User");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return User_1.User; } });
