"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertOneTodoItemResolver = exports.UpdateOneTodoItemResolver = exports.UpdateManyTodoItemResolver = exports.GroupByTodoItemResolver = exports.FindUniqueTodoItemOrThrowResolver = exports.FindUniqueTodoItemResolver = exports.FindManyTodoItemResolver = exports.FindFirstTodoItemOrThrowResolver = exports.FindFirstTodoItemResolver = exports.DeleteOneTodoItemResolver = exports.DeleteManyTodoItemResolver = exports.CreateOneTodoItemResolver = exports.AggregateTodoItemResolver = void 0;
var AggregateTodoItemResolver_1 = require("./TodoItem/AggregateTodoItemResolver");
Object.defineProperty(exports, "AggregateTodoItemResolver", { enumerable: true, get: function () { return AggregateTodoItemResolver_1.AggregateTodoItemResolver; } });
var CreateOneTodoItemResolver_1 = require("./TodoItem/CreateOneTodoItemResolver");
Object.defineProperty(exports, "CreateOneTodoItemResolver", { enumerable: true, get: function () { return CreateOneTodoItemResolver_1.CreateOneTodoItemResolver; } });
var DeleteManyTodoItemResolver_1 = require("./TodoItem/DeleteManyTodoItemResolver");
Object.defineProperty(exports, "DeleteManyTodoItemResolver", { enumerable: true, get: function () { return DeleteManyTodoItemResolver_1.DeleteManyTodoItemResolver; } });
var DeleteOneTodoItemResolver_1 = require("./TodoItem/DeleteOneTodoItemResolver");
Object.defineProperty(exports, "DeleteOneTodoItemResolver", { enumerable: true, get: function () { return DeleteOneTodoItemResolver_1.DeleteOneTodoItemResolver; } });
var FindFirstTodoItemResolver_1 = require("./TodoItem/FindFirstTodoItemResolver");
Object.defineProperty(exports, "FindFirstTodoItemResolver", { enumerable: true, get: function () { return FindFirstTodoItemResolver_1.FindFirstTodoItemResolver; } });
var FindFirstTodoItemOrThrowResolver_1 = require("./TodoItem/FindFirstTodoItemOrThrowResolver");
Object.defineProperty(exports, "FindFirstTodoItemOrThrowResolver", { enumerable: true, get: function () { return FindFirstTodoItemOrThrowResolver_1.FindFirstTodoItemOrThrowResolver; } });
var FindManyTodoItemResolver_1 = require("./TodoItem/FindManyTodoItemResolver");
Object.defineProperty(exports, "FindManyTodoItemResolver", { enumerable: true, get: function () { return FindManyTodoItemResolver_1.FindManyTodoItemResolver; } });
var FindUniqueTodoItemResolver_1 = require("./TodoItem/FindUniqueTodoItemResolver");
Object.defineProperty(exports, "FindUniqueTodoItemResolver", { enumerable: true, get: function () { return FindUniqueTodoItemResolver_1.FindUniqueTodoItemResolver; } });
var FindUniqueTodoItemOrThrowResolver_1 = require("./TodoItem/FindUniqueTodoItemOrThrowResolver");
Object.defineProperty(exports, "FindUniqueTodoItemOrThrowResolver", { enumerable: true, get: function () { return FindUniqueTodoItemOrThrowResolver_1.FindUniqueTodoItemOrThrowResolver; } });
var GroupByTodoItemResolver_1 = require("./TodoItem/GroupByTodoItemResolver");
Object.defineProperty(exports, "GroupByTodoItemResolver", { enumerable: true, get: function () { return GroupByTodoItemResolver_1.GroupByTodoItemResolver; } });
var UpdateManyTodoItemResolver_1 = require("./TodoItem/UpdateManyTodoItemResolver");
Object.defineProperty(exports, "UpdateManyTodoItemResolver", { enumerable: true, get: function () { return UpdateManyTodoItemResolver_1.UpdateManyTodoItemResolver; } });
var UpdateOneTodoItemResolver_1 = require("./TodoItem/UpdateOneTodoItemResolver");
Object.defineProperty(exports, "UpdateOneTodoItemResolver", { enumerable: true, get: function () { return UpdateOneTodoItemResolver_1.UpdateOneTodoItemResolver; } });
var UpsertOneTodoItemResolver_1 = require("./TodoItem/UpsertOneTodoItemResolver");
Object.defineProperty(exports, "UpsertOneTodoItemResolver", { enumerable: true, get: function () { return UpsertOneTodoItemResolver_1.UpsertOneTodoItemResolver; } });
