"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateManyUserResolver = exports.GroupByUserResolver = exports.FindUniqueUserOrThrowResolver = exports.FindUniqueUserResolver = exports.FindManyUserResolver = exports.FindFirstUserOrThrowResolver = exports.FindFirstUserResolver = exports.DeleteOneUserResolver = exports.DeleteManyUserResolver = exports.CreateOneUserResolver = exports.AggregateUserResolver = exports.UpsertOnePostHistoryResolver = exports.UpdateOnePostHistoryResolver = exports.UpdateManyPostHistoryResolver = exports.GroupByPostHistoryResolver = exports.FindUniquePostHistoryOrThrowResolver = exports.FindUniquePostHistoryResolver = exports.FindManyPostHistoryResolver = exports.FindFirstPostHistoryOrThrowResolver = exports.FindFirstPostHistoryResolver = exports.DeleteOnePostHistoryResolver = exports.DeleteManyPostHistoryResolver = exports.CreateOnePostHistoryResolver = exports.AggregatePostHistoryResolver = exports.UpsertOnePostResolver = exports.UpdateOnePostResolver = exports.UpdateManyPostResolver = exports.GroupByPostResolver = exports.FindUniquePostOrThrowResolver = exports.FindUniquePostResolver = exports.FindManyPostResolver = exports.FindFirstPostOrThrowResolver = exports.FindFirstPostResolver = exports.DeleteOnePostResolver = exports.DeleteManyPostResolver = exports.CreateOnePostResolver = exports.AggregatePostResolver = exports.UpsertOneCommentResolver = exports.UpdateOneCommentResolver = exports.UpdateManyCommentResolver = exports.GroupByCommentResolver = exports.FindUniqueCommentOrThrowResolver = exports.FindUniqueCommentResolver = exports.FindManyCommentResolver = exports.FindFirstCommentOrThrowResolver = exports.FindFirstCommentResolver = exports.DeleteOneCommentResolver = exports.DeleteManyCommentResolver = exports.CreateOneCommentResolver = exports.AggregateCommentResolver = void 0;
exports.UpsertOneUserResolver = exports.UpdateOneUserResolver = void 0;
var AggregateCommentResolver_1 = require("./Comment/AggregateCommentResolver");
Object.defineProperty(exports, "AggregateCommentResolver", { enumerable: true, get: function () { return AggregateCommentResolver_1.AggregateCommentResolver; } });
var CreateOneCommentResolver_1 = require("./Comment/CreateOneCommentResolver");
Object.defineProperty(exports, "CreateOneCommentResolver", { enumerable: true, get: function () { return CreateOneCommentResolver_1.CreateOneCommentResolver; } });
var DeleteManyCommentResolver_1 = require("./Comment/DeleteManyCommentResolver");
Object.defineProperty(exports, "DeleteManyCommentResolver", { enumerable: true, get: function () { return DeleteManyCommentResolver_1.DeleteManyCommentResolver; } });
var DeleteOneCommentResolver_1 = require("./Comment/DeleteOneCommentResolver");
Object.defineProperty(exports, "DeleteOneCommentResolver", { enumerable: true, get: function () { return DeleteOneCommentResolver_1.DeleteOneCommentResolver; } });
var FindFirstCommentResolver_1 = require("./Comment/FindFirstCommentResolver");
Object.defineProperty(exports, "FindFirstCommentResolver", { enumerable: true, get: function () { return FindFirstCommentResolver_1.FindFirstCommentResolver; } });
var FindFirstCommentOrThrowResolver_1 = require("./Comment/FindFirstCommentOrThrowResolver");
Object.defineProperty(exports, "FindFirstCommentOrThrowResolver", { enumerable: true, get: function () { return FindFirstCommentOrThrowResolver_1.FindFirstCommentOrThrowResolver; } });
var FindManyCommentResolver_1 = require("./Comment/FindManyCommentResolver");
Object.defineProperty(exports, "FindManyCommentResolver", { enumerable: true, get: function () { return FindManyCommentResolver_1.FindManyCommentResolver; } });
var FindUniqueCommentResolver_1 = require("./Comment/FindUniqueCommentResolver");
Object.defineProperty(exports, "FindUniqueCommentResolver", { enumerable: true, get: function () { return FindUniqueCommentResolver_1.FindUniqueCommentResolver; } });
var FindUniqueCommentOrThrowResolver_1 = require("./Comment/FindUniqueCommentOrThrowResolver");
Object.defineProperty(exports, "FindUniqueCommentOrThrowResolver", { enumerable: true, get: function () { return FindUniqueCommentOrThrowResolver_1.FindUniqueCommentOrThrowResolver; } });
var GroupByCommentResolver_1 = require("./Comment/GroupByCommentResolver");
Object.defineProperty(exports, "GroupByCommentResolver", { enumerable: true, get: function () { return GroupByCommentResolver_1.GroupByCommentResolver; } });
var UpdateManyCommentResolver_1 = require("./Comment/UpdateManyCommentResolver");
Object.defineProperty(exports, "UpdateManyCommentResolver", { enumerable: true, get: function () { return UpdateManyCommentResolver_1.UpdateManyCommentResolver; } });
var UpdateOneCommentResolver_1 = require("./Comment/UpdateOneCommentResolver");
Object.defineProperty(exports, "UpdateOneCommentResolver", { enumerable: true, get: function () { return UpdateOneCommentResolver_1.UpdateOneCommentResolver; } });
var UpsertOneCommentResolver_1 = require("./Comment/UpsertOneCommentResolver");
Object.defineProperty(exports, "UpsertOneCommentResolver", { enumerable: true, get: function () { return UpsertOneCommentResolver_1.UpsertOneCommentResolver; } });
var AggregatePostResolver_1 = require("./Post/AggregatePostResolver");
Object.defineProperty(exports, "AggregatePostResolver", { enumerable: true, get: function () { return AggregatePostResolver_1.AggregatePostResolver; } });
var CreateOnePostResolver_1 = require("./Post/CreateOnePostResolver");
Object.defineProperty(exports, "CreateOnePostResolver", { enumerable: true, get: function () { return CreateOnePostResolver_1.CreateOnePostResolver; } });
var DeleteManyPostResolver_1 = require("./Post/DeleteManyPostResolver");
Object.defineProperty(exports, "DeleteManyPostResolver", { enumerable: true, get: function () { return DeleteManyPostResolver_1.DeleteManyPostResolver; } });
var DeleteOnePostResolver_1 = require("./Post/DeleteOnePostResolver");
Object.defineProperty(exports, "DeleteOnePostResolver", { enumerable: true, get: function () { return DeleteOnePostResolver_1.DeleteOnePostResolver; } });
var FindFirstPostResolver_1 = require("./Post/FindFirstPostResolver");
Object.defineProperty(exports, "FindFirstPostResolver", { enumerable: true, get: function () { return FindFirstPostResolver_1.FindFirstPostResolver; } });
var FindFirstPostOrThrowResolver_1 = require("./Post/FindFirstPostOrThrowResolver");
Object.defineProperty(exports, "FindFirstPostOrThrowResolver", { enumerable: true, get: function () { return FindFirstPostOrThrowResolver_1.FindFirstPostOrThrowResolver; } });
var FindManyPostResolver_1 = require("./Post/FindManyPostResolver");
Object.defineProperty(exports, "FindManyPostResolver", { enumerable: true, get: function () { return FindManyPostResolver_1.FindManyPostResolver; } });
var FindUniquePostResolver_1 = require("./Post/FindUniquePostResolver");
Object.defineProperty(exports, "FindUniquePostResolver", { enumerable: true, get: function () { return FindUniquePostResolver_1.FindUniquePostResolver; } });
var FindUniquePostOrThrowResolver_1 = require("./Post/FindUniquePostOrThrowResolver");
Object.defineProperty(exports, "FindUniquePostOrThrowResolver", { enumerable: true, get: function () { return FindUniquePostOrThrowResolver_1.FindUniquePostOrThrowResolver; } });
var GroupByPostResolver_1 = require("./Post/GroupByPostResolver");
Object.defineProperty(exports, "GroupByPostResolver", { enumerable: true, get: function () { return GroupByPostResolver_1.GroupByPostResolver; } });
var UpdateManyPostResolver_1 = require("./Post/UpdateManyPostResolver");
Object.defineProperty(exports, "UpdateManyPostResolver", { enumerable: true, get: function () { return UpdateManyPostResolver_1.UpdateManyPostResolver; } });
var UpdateOnePostResolver_1 = require("./Post/UpdateOnePostResolver");
Object.defineProperty(exports, "UpdateOnePostResolver", { enumerable: true, get: function () { return UpdateOnePostResolver_1.UpdateOnePostResolver; } });
var UpsertOnePostResolver_1 = require("./Post/UpsertOnePostResolver");
Object.defineProperty(exports, "UpsertOnePostResolver", { enumerable: true, get: function () { return UpsertOnePostResolver_1.UpsertOnePostResolver; } });
var AggregatePostHistoryResolver_1 = require("./PostHistory/AggregatePostHistoryResolver");
Object.defineProperty(exports, "AggregatePostHistoryResolver", { enumerable: true, get: function () { return AggregatePostHistoryResolver_1.AggregatePostHistoryResolver; } });
var CreateOnePostHistoryResolver_1 = require("./PostHistory/CreateOnePostHistoryResolver");
Object.defineProperty(exports, "CreateOnePostHistoryResolver", { enumerable: true, get: function () { return CreateOnePostHistoryResolver_1.CreateOnePostHistoryResolver; } });
var DeleteManyPostHistoryResolver_1 = require("./PostHistory/DeleteManyPostHistoryResolver");
Object.defineProperty(exports, "DeleteManyPostHistoryResolver", { enumerable: true, get: function () { return DeleteManyPostHistoryResolver_1.DeleteManyPostHistoryResolver; } });
var DeleteOnePostHistoryResolver_1 = require("./PostHistory/DeleteOnePostHistoryResolver");
Object.defineProperty(exports, "DeleteOnePostHistoryResolver", { enumerable: true, get: function () { return DeleteOnePostHistoryResolver_1.DeleteOnePostHistoryResolver; } });
var FindFirstPostHistoryResolver_1 = require("./PostHistory/FindFirstPostHistoryResolver");
Object.defineProperty(exports, "FindFirstPostHistoryResolver", { enumerable: true, get: function () { return FindFirstPostHistoryResolver_1.FindFirstPostHistoryResolver; } });
var FindFirstPostHistoryOrThrowResolver_1 = require("./PostHistory/FindFirstPostHistoryOrThrowResolver");
Object.defineProperty(exports, "FindFirstPostHistoryOrThrowResolver", { enumerable: true, get: function () { return FindFirstPostHistoryOrThrowResolver_1.FindFirstPostHistoryOrThrowResolver; } });
var FindManyPostHistoryResolver_1 = require("./PostHistory/FindManyPostHistoryResolver");
Object.defineProperty(exports, "FindManyPostHistoryResolver", { enumerable: true, get: function () { return FindManyPostHistoryResolver_1.FindManyPostHistoryResolver; } });
var FindUniquePostHistoryResolver_1 = require("./PostHistory/FindUniquePostHistoryResolver");
Object.defineProperty(exports, "FindUniquePostHistoryResolver", { enumerable: true, get: function () { return FindUniquePostHistoryResolver_1.FindUniquePostHistoryResolver; } });
var FindUniquePostHistoryOrThrowResolver_1 = require("./PostHistory/FindUniquePostHistoryOrThrowResolver");
Object.defineProperty(exports, "FindUniquePostHistoryOrThrowResolver", { enumerable: true, get: function () { return FindUniquePostHistoryOrThrowResolver_1.FindUniquePostHistoryOrThrowResolver; } });
var GroupByPostHistoryResolver_1 = require("./PostHistory/GroupByPostHistoryResolver");
Object.defineProperty(exports, "GroupByPostHistoryResolver", { enumerable: true, get: function () { return GroupByPostHistoryResolver_1.GroupByPostHistoryResolver; } });
var UpdateManyPostHistoryResolver_1 = require("./PostHistory/UpdateManyPostHistoryResolver");
Object.defineProperty(exports, "UpdateManyPostHistoryResolver", { enumerable: true, get: function () { return UpdateManyPostHistoryResolver_1.UpdateManyPostHistoryResolver; } });
var UpdateOnePostHistoryResolver_1 = require("./PostHistory/UpdateOnePostHistoryResolver");
Object.defineProperty(exports, "UpdateOnePostHistoryResolver", { enumerable: true, get: function () { return UpdateOnePostHistoryResolver_1.UpdateOnePostHistoryResolver; } });
var UpsertOnePostHistoryResolver_1 = require("./PostHistory/UpsertOnePostHistoryResolver");
Object.defineProperty(exports, "UpsertOnePostHistoryResolver", { enumerable: true, get: function () { return UpsertOnePostHistoryResolver_1.UpsertOnePostHistoryResolver; } });
var AggregateUserResolver_1 = require("./User/AggregateUserResolver");
Object.defineProperty(exports, "AggregateUserResolver", { enumerable: true, get: function () { return AggregateUserResolver_1.AggregateUserResolver; } });
var CreateOneUserResolver_1 = require("./User/CreateOneUserResolver");
Object.defineProperty(exports, "CreateOneUserResolver", { enumerable: true, get: function () { return CreateOneUserResolver_1.CreateOneUserResolver; } });
var DeleteManyUserResolver_1 = require("./User/DeleteManyUserResolver");
Object.defineProperty(exports, "DeleteManyUserResolver", { enumerable: true, get: function () { return DeleteManyUserResolver_1.DeleteManyUserResolver; } });
var DeleteOneUserResolver_1 = require("./User/DeleteOneUserResolver");
Object.defineProperty(exports, "DeleteOneUserResolver", { enumerable: true, get: function () { return DeleteOneUserResolver_1.DeleteOneUserResolver; } });
var FindFirstUserResolver_1 = require("./User/FindFirstUserResolver");
Object.defineProperty(exports, "FindFirstUserResolver", { enumerable: true, get: function () { return FindFirstUserResolver_1.FindFirstUserResolver; } });
var FindFirstUserOrThrowResolver_1 = require("./User/FindFirstUserOrThrowResolver");
Object.defineProperty(exports, "FindFirstUserOrThrowResolver", { enumerable: true, get: function () { return FindFirstUserOrThrowResolver_1.FindFirstUserOrThrowResolver; } });
var FindManyUserResolver_1 = require("./User/FindManyUserResolver");
Object.defineProperty(exports, "FindManyUserResolver", { enumerable: true, get: function () { return FindManyUserResolver_1.FindManyUserResolver; } });
var FindUniqueUserResolver_1 = require("./User/FindUniqueUserResolver");
Object.defineProperty(exports, "FindUniqueUserResolver", { enumerable: true, get: function () { return FindUniqueUserResolver_1.FindUniqueUserResolver; } });
var FindUniqueUserOrThrowResolver_1 = require("./User/FindUniqueUserOrThrowResolver");
Object.defineProperty(exports, "FindUniqueUserOrThrowResolver", { enumerable: true, get: function () { return FindUniqueUserOrThrowResolver_1.FindUniqueUserOrThrowResolver; } });
var GroupByUserResolver_1 = require("./User/GroupByUserResolver");
Object.defineProperty(exports, "GroupByUserResolver", { enumerable: true, get: function () { return GroupByUserResolver_1.GroupByUserResolver; } });
var UpdateManyUserResolver_1 = require("./User/UpdateManyUserResolver");
Object.defineProperty(exports, "UpdateManyUserResolver", { enumerable: true, get: function () { return UpdateManyUserResolver_1.UpdateManyUserResolver; } });
var UpdateOneUserResolver_1 = require("./User/UpdateOneUserResolver");
Object.defineProperty(exports, "UpdateOneUserResolver", { enumerable: true, get: function () { return UpdateOneUserResolver_1.UpdateOneUserResolver; } });
var UpsertOneUserResolver_1 = require("./User/UpsertOneUserResolver");
Object.defineProperty(exports, "UpsertOneUserResolver", { enumerable: true, get: function () { return UpsertOneUserResolver_1.UpsertOneUserResolver; } });
